#!/usr/bin/env bash
tmux source ~/.tmux.conf \; new-session -n "console" -s "Workspace 1" \; \
    split-window -h \; split-window \; \
    send-keys -t 1 "gotop" Enter \; \
    send-keys -t 0 "cleanwttr" Enter \; \
    rename-window "console"
