#+TITLE: Polybar Configuration
#+PROPERTY: header-args :tangle config
#+STARTUP: showeverything


* Table Of Content :toc:
- [[#colors][Colors]]
- [[#base][Base]]
- [[#modules][Modules]]
  - [[#any-new-updates][Any new Updates?]]
  - [[#is-zoom-running][Is Zoom running?]]
  - [[#how-much-will-i-earn-this-month][How much will i earn this month?]]
  - [[#when-was-passwords-updated-last][When was passwords updated last?]]
  - [[#timer][Timer]]
  - [[#is-git-projects-pushed][Is Git projects pushed?]]
  - [[#bluetooth-connections][Bluetooth connections?]]
  - [[#network][Network]]
  - [[#date--time][Date / Time]]
  - [[#battery][Battery]]
  - [[#volume][Volume]]
  - [[#internet--essid][Internet / ESSID]]
  - [[#workspaces][Workspaces]]
- [[#launch-script][Launch script]]

* Colors
#+BEGIN_SRC conf
[colors]

bar_bg = ${xrdb:background}
bar_fg = ${xrdb:foreground}

border_col = ${xrdb:background}

modules_bg = ${xrdb:color7}
modules_fg = ${xrdb:color0}

mod_bg = ${xrdb:color7}

modules_prefix_bg = ${xrdb:color7}
modules_prefix_fg = ${xrdb:color0}

urgent_bg  = ${xrdb:color1}
focused_bg = ${xrdb:color10}

essid_p_bg   = ${xrdb:color6}
down_p_bg    = #5e606c
cpu_p_bg     = ${xrdb:color5}
ram_p_bg     = ${xrdb:color11}
vol_p_bg     = #637b81
bright_p_bg  = #c29f6f
battery_p_bg = ${xrdb:color9}
time_p_bg    = ${xrdb:color10}
#+END_SRC
* Base
#+BEGIN_SRC conf
[bar/base]
dpi      = 192
width    = 100%
height   = 20
offset-x = 0
offset-y = 0

bottom = true

;background = #00FFFFFF
background = ${xrdb:background}
foreground = ${xrdb:foreground}

border-bottom-size  = 0
border-top-size     = 0

border-left-size  = 0
border-right-size = 0

border-bottom-color = ${xrdb:background}
border-top-color    = ${xrdb:background}

border-left-color = ${xrdb:background}
border-right-colo = ${xrdb:background}
spacing            = 0
padding-left       = 1
padding-right      = 1
module-margin-left = 0

font-1 = SauceCodePro Nerd Font:size=4;2
font-0 = Source Code Pro:size=4;2

modules-left   = workspaces
modules-center = gitPushed newUpdates passAge zoomRunning
modules-right  = clockifySalary timer bluetooth essid volume battery date

fixed-center = true
#+END_SRC

* Modules
** Any new Updates?
#+BEGIN_SRC conf
[module/newUpdates]
type = custom/script
exec = ~/.config/polybar/any_updates.sh
interval = 600
format-padding = 1
format-foreground = ${xrdb:color1}
#+END_SRC
*** The underlying script
#+BEGIN_SRC conf :tangle any_updates.sh :shebang #!/bin/sh
if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$updates" -gt 0 ]; then
echo "ﮮ $updates"
else
echo ""
fi

#+END_SRC

** Is Zoom running?
#+BEGIN_SRC conf
[module/zoomRunning]
	type = custom/script
	exec = "pgrep zoom > /dev/null && echo ' ' || echo ''"
	interval = 1
	format-padding = 1
	format-foreground = ${xrdb:color1}
#+END_SRC
** How much will i earn this month?
#+BEGIN_SRC conf
[module/clockifySalary]
	type = custom/script
	exec = "~/bin/clockify_hours.py"
	interval = 600
	format-padding = 1
#+END_SRC

** When was passwords updated last?
I use this script to remembr to delete old unused account and redo passwords
once in a while for good measure.
However this requires you to be running [[https://www.passwordstore.org/][pass]] as your password manager.
#+BEGIN_SRC conf
[module/passAge]
	type = custom/script
	exec = "~/bin/passage | wc -l"
	exec-if = "(( $(~/bin/passage | wc -l) > 0 ))"
	format =  <label>
	interval = 60
	format-padding = 1
	format-foreground = ${xrdb:color1}
#+END_SRC

** Timer
I created a small timer script. Rarely use it, but you can if you install all scripts.
#+BEGIN_SRC conf
[module/timer]
	type = custom/script
	exec = ~/bin/timer_read
	interval = 1
	format-padding = 1
	format-foreground = ${xrdb:color5}
#+END_SRC
** Is Git projects pushed?
Small script that checks whether my varous git repositories has uncommited changes.
#+BEGIN_SRC conf
[module/gitPushed]
	type = custom/script
	exec = ~/.config/polybar/is_git_pushed.sh
	interval = 4
	format-padding = 1
	format-foreground = ${xrdb:color1}
#+END_SRC
*** The underlying script
#+BEGIN_SRC conf :tangle is_git_pushed.sh :shebang #!/bin/sh
repos=""

issync() {
  cd $1
	if [ $(git status | grep "nothing to commit" | wc -c) -eq 0 ]
	then
		repos="$repos $(echo "$1" | sed 's/.*\///g')"
	fi
}

for file in ~/dev/*; do
	if [ -d "$file/.git" ]; then
	   issync "$file"
	fi
done

issync ~/.dotfiles
issync ~/.password-store
issync ~/Documents

if [ ! -z "$repos" ]
then
	echo "$repos"
else
	echo ""
fi

#+END_SRC

** Bluetooth connections?
#+BEGIN_SRC conf
[module/bluetooth]
	type = custom/script
	exec = ~/.config/polybar/bluetooth.sh
	interval = 2
	format-padding = 1
	format-foreground = ${xrdb:foreground}
#+END_SRC
*** The underlying script
#+BEGIN_SRC conf :tangle bluetooth.sh :shebang #!/bin/sh
if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
then
	echo ""
else
	echo " $(bluetoothctl info | grep "Name: " | sed 's/\W*Name://g')"
fi
#+END_SRC
** Network
#+BEGIN_SRC conf
[module/network]
	type          = internal/network
	interface     = wlp1s0
	ping-interval = 3
#+END_SRC
** Date / Time
#+BEGIN_SRC conf
[module/date]
	type     = internal/date
	interval = 1.0
	time     = "W-%W %Y-%m-%d %H:%M"
	label    = "   %time%"

	format         = <label>
	format-padding = 0

	label-foreground = ${xrdb:foreground}
	label-padding    = 0
#+END_SRC
** Battery
#+BEGIN_SRC conf

[module/battery]
	type          = internal/battery
	full-at       = 98
	battery       = BAT0
	adapter       = AC0
	poll-interval = 5

	format-charging = <label-charging>

	label-charging            = "%percentage%%"
	format-charging-prefix            = "⚡"
	format-charging-prefix-foreground = ${xrdb:color3}
	format-charging-prefix-padding    = 1
	label-charging-foreground = ${xrdb:foreground}
	label-charging-padding    = 1

	label-discharging            = "%percentage%%"
	format-discharging = <ramp-capacity> <label-discharging>
	format-discharging-prefix-foreground = ${xrdb:foreground}
	format-discharging-prefix-padding    = 1

	label-discharging-foreground = ${xrdb:foreground}
	label-discharging-padding    = 1
	ramp-capacity-0 = 
	ramp-capacity-1 = 
	ramp-capacity-2 = 
	ramp-capacity-3 = 
	ramp-capacity-4 = 
	ramp-capacity-0-foreground = ${xrdb:color1}
	ramp-capacity-1-foreground = ${xrdb:color1}


	format-full = <label-full>
	format-full-prefix            = ""
	format-full-prefix-foreground = ${xrdb:foreground}
	format-full-prefix-padding    = 1
   
	label-full            = "%percentage%%"
	label-full-foreground = ${xrdb:foreground}
	label-full-padding    = 1
#+END_SRC
** Volume
#+BEGIN_SRC conf
[module/volume]
	type          = internal/alsa
	format-volume = <label-volume>

	master-soundcard = default
	speaker-soundcard = default
	headphone-soundcard = default

	master-mixer = Master

	label-volume            = " %percentage%%"
	label-volume-foreground = ${xrdb:foreground}
	label-volume-padding    = 3

	format-muted = <label-muted>

	label-muted            = " 0%"
	label-muted-foreground = ${xrdb:foreground}
	label-muted-padding    = 3

	format-volume-padding = 0
	format-muted-padding  = 0

	ramp-headphones-0 = 

#+END_SRC
** Internet / ESSID
#+BEGIN_SRC conf
[module/essid]
	inherit = module/network

	format-connected = <label-connected>

	format-connected-prefix            = ""
	format-connected-prefix-padding    = 1
	format-connected-prefix-foreground = ${xrdb:color2}

	label-connected            = "%essid% "
	label-connected-foreground = ${xrdb:foreground}
	label-connected-padding    = 1

	ramp-signal-foreground    = ${xrdb:foreground}
	ramp-connected-foreground = ${xrdb:foreground}
	ramp-signal-padding       = 1

	format-disconnected = <label-disconnected>

	format-disconnected-prefix            = ""
	format-disconnected-prefix-padding    = 1
	format-disconnected-prefix-foreground = ${xrdb:foreground}

	label-disconnected            = "DISCONNECTED"
	label-disconnected-foreground = ${xrdb:foreground}
	label-disconnected-padding    = 1
#+END_SRC

** Workspaces
#+BEGIN_SRC conf
[module/workspaces]
	type            = internal/i3
	format          = <label-state> <label-mode>
	index-sort      = true
	wrapping-scroll = false
	strip-wsnumbers = true

	label-mode-background = ${xrdb:color7}
	label-mode-foreground = ${xrdb:background}
	label-mode-padding    = 2

	label-focused            = %name%
	label-focused-foreground = ${xrdb:foreground}
	label-focused-padding    = 2

	label-unfocused            = %name%
	label-unfocused-foreground = ${xrdb:color0}
	label-unfocused-padding    = 2

	label-visible            = %name%
	label-visible-foreground = ${xrdb:color7}
	label-visible-padding    = 2

	label-urgent            = %name%
	label-urgent-foreground = ${xrdb:color1}
	label-urgent-padding    = 2
#+END_SRC
* Launch script
#+BEGIN_SRC sh :tangle launch.sh :shebang #!/bin/sh
if ! pgrep -x polybar; then
	polybar base &
else
	pkill -USR1 polybar
fi

echo "Bars launched..."
#+END_SRC
Script used to launch the application
